### ISSUE TITLE
Windows cmake build issues

### ISSUE THREAD

**Issue by antopilo** [michaeljclark/glyb#2]
Building introspection files on Windows requires BUILD_SHARED_LIBS to be enabled.
-- Configuring done
CMake Error: install(EXPORT "libpng" ...) includes target "png" which requires target "zlibstatic" that is not in any export set.
CMake Error: install(EXPORT "libpng" ...) includes target "png_static" which requires target "zlibstatic" that is not in any export set.
-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.

**Comment by larkmjc** [comment]
I've retitled the bug to reflect that Windows CMake works under some circumstances. I have encountered this issue too but can't remember off hand how I patched it locally. It may require some changes upstream in libpng or zlibstatic.

possibly could be fixed with a strategically placed `export(EXPORT zlibstatic)`
